name: test 001

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Generate badge data
      id: badge_data
      run: |
        VALUE=$(date -u +'%Y-%m-%d %H:%M:%S')
        echo "value=$VALUE" >> $GITHUB_OUTPUT

    - name: Fetch Guardian News
      id: fetch_news
      run: |
        VALUE=$(date -u +'%Y-%m-%d %H:%M:%S')
        echo "value=$VALUE" >> $GITHUB_OUTPUT

        API_KEY=${{ secrets.GUARDIAN_KEY }} 
        URL="https://content.guardianapis.com/search"
        ORDER_BY="newest"  
        PAGE_SIZE=5
        response=$(curl -s -G \
            --data-urlencode "api-key=$API_KEY" \
            --data-urlencode "order-by=$ORDER_BY" \
            --data-urlencode "page-size=$PAGE_SIZE" \
            "$URL")
        echo "response=$response" >> $GITHUB_OUTPUT

        sorted_data=$(echo "$response" | jq -r '.response.results | sort_by(.webPublicationDate) | .[] | [.webPublicationDate, .sectionName, .pillarName, .type, .webTitle, .webUrl] | @tsv')

        while IFS=$'\t' read -r webPublicationDate sectionName pillarName type webTitle webUrl; do
          date -d "$webPublicationDate" 

        done < <(echo "$sorted_data")

    - name: Process News
      id: process_news
      run: |
        CURRENT=$(date -u +'%s')
        echo "current=$CURRENT" >> $GITHUB_OUTPUT
        echo ${{ steps.fetch_news.outputs.response }}


    - name: Send Telegram messsage
      uses: stellarhub/telegram-message-action@v1
      with:
        chat_id: ${{ vars.TELEGRAM_CHANNEL_ID }}
        token: ${{ secrets.TELEGRAM_BOT_KEY }}
        message: ${{ steps.process_news.outputs.current }}
